#!/bin/bash

TERRAFORM="/bin/terraform_0.12.29"

export AWS_REGION=us-east-1
export AWS_PROFILE=lab
export AWS_SHARED_CREDENTIALS_FILE=~/.aws/credentials

$TERRAFORM init

$TERRAFORM get -update

$TERRAFORM $@ 

